services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: news
      POSTGRES_PASSWORD: news
    volumes: [dbdata:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./backend
    image: news-backend:dev
    env_file: ./backend/.env
    depends_on: [db, redis]
    volumes: ["./backend:/var/www/html"]

  web:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: [api]
    ports: ["9000:80"]

  queue:
    image: news-backend:dev
    command: php artisan queue:work --tries=3 --timeout=120
    env_file: ./backend/.env
    depends_on: [api, redis, db]
    volumes: ["./backend:/var/www/html"]

  scheduler:
    image: news-backend:dev
    command: sh -c 'while :; do php artisan schedule:run; sleep 60; done'
    env_file: ./backend/.env
    depends_on: [api, db, redis]
    volumes: ["./backend:/var/www/html"]

  frontend:
    build: ./frontend
    depends_on: [api]
    ports: ["5173:80"]
volumes:
  dbdata:
